### ISSUE TITLE
v2.68 Fails to import k8s

### ISSUE THREAD

**Issue by payam54** [cdk8s-team/cdk8s-cli#1323]
### Description of the bug:

I tried versions `2.68.0` and `2.68.1` and both fail `import k8s`. By pinning the version of `cdk8s-cli` to `2.67.0` in my Dockerfile, it all went through without any issues.

### Reproduction Steps:

Build from Dockerfile:
```
FROM node:18.2.0-alpine AS node
FROM dockerhub.docker.artifactory.viasat.com/alpine:3.12.0
RUN apk update && apk upgrade && apk add py3-setuptools && apk add --update py-pip && \
    apk add --no-cache gcc linux-headers musl-dev bash python3-dev 
RUN python3 -m pip install cdk8s
RUN npm cache clean -f
RUN npm install -g cdk8s-cli@2.68.0
RUN cdk8s import k8s@1.22.0 --language python
```

### Error Log:

```
[stage-1 14/14] RUN cdk8s import k8s@1.22.0 --language python
12:36:23  #20 1.564 Importing k8s v1.22.0...
12:36:23  #20 1.575 Importing resources, this may take a few moments...
12:36:23  #20 1.576 k8s
12:36:33  #20 11.59 Error: ENOENT: no such file or directory, open 'cdk8s.yaml'
12:36:33  #20 11.59     at Object.openSync (node:fs:591:3)
12:36:33  #20 11.59     at Object.readFileSync (node:fs:459:35)
12:36:33  #20 11.59     at addImportToConfig (/usr/local/lib/node_modules/cdk8s-cli/lib/config.js:49:35)
12:36:33  #20 11.59     at importDispatch (/usr/local/lib/node_modules/cdk8s-cli/lib/import/dispatch.js:23:50)
12:36:33  #20 11.59     at async Object.handler (/usr/local/lib/node_modules/cdk8s-cli/lib/cli/cmds/import.js:32:9) {
12:36:33  #20 11.59   errno: -2,
12:36:33  #20 11.59   syscall: 'open',
12:36:33  #20 11.59   code: 'ENOENT',
12:36:33  #20 11.59   path: 'cdk8s.yaml'
12:36:33  #20 11.59 }
12:36:33  #20 ERROR: process "/bin/sh -c cdk8s import k8s@1.22.0 --language python" did not complete successfully: exit code: 1
```

---

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@payam54 

Interesting, we never considered `cdk8s import` to be executed outside of a cdk8s application, i.e without running `cdk8s init`. There's no reason for it to fail nonetheless, thanks for reporting this!

**Comment by iliapolo** [comment]
@payam54 in the meantime, you can use the `--no-save` option to workaround the issue.

```console
cdk8s import --no-save --language python k8s@1.22.0
```
