### ISSUE TITLE
Loading github:rabbitmq/cluster-operator causes 'unsupported protocol: github'

### ISSUE THREAD

**Issue by dragonpaw** [cdk8s-team/cdk8s-cli#1467]
### Description of the bug:

Loading RabbitMQ CRD causes 'unsupported protocol: github' error.

### Reproduction Steps:

```console
$ cdk8s import github:rabbitmq/cluster-operator@v2.1.0
```

### Error Log:

```
------------------------------------------------------------------------------------------------
A new version 2.118.0 of cdk8s-cli is available (current 2.116.0).
Run "npm install -g cdk8s-cli" to install the latest version on your system.
For additional installation methods, see https://cdk8s.io/docs/latest/getting-started
------------------------------------------------------------------------------------------------
Error: unsupported protocol github:
    at download (/usr/local/Cellar/cdk8s/2.116.0/libexec/lib/node_modules/cdk8s-cli/lib/util.js:177:19)
    at ImportCustomResourceDefinition.fromSpec (/usr/local/Cellar/cdk8s/2.116.0/libexec/lib/node_modules/cdk8s-cli/lib/import/crd.js:108:52)
    at matchImporter (/usr/local/Cellar/cdk8s/2.116.0/libexec/lib/node_modules/cdk8s-cli/lib/import/dispatch.js:40:49)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async importDispatch (/usr/local/Cellar/cdk8s/2.116.0/libexec/lib/node_modules/cdk8s-cli/lib/import/dispatch.js:12:26)
    at async Object.handler (/usr/local/Cellar/cdk8s/2.116.0/libexec/lib/node_modules/cdk8s-cli/lib/cli/cmds/import.js:32:9)
```

### Environment:

  - **Framework Version**: 
  - **OS**: MacOS, using 'brew' build version of cdk8s

---

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@dragonpaw you need to remove the `v` from the version:

```console
❯ cdk8s import github:rabbitmq/cluster-operator@2.1.0                                                                                                                                                                                    [02:48:15]
Importing resources, this may take a few moments...
rabbitmq.com
  rabbitmq.com/rabbitmqcluster
```

Otherwise it thinks its a regular URL, instead of a doc.crds.dev one.
