### ISSUE TITLE
cdk8s import helm with OCI format fails

### ISSUE THREAD

**Issue by fletcm** [cdk8s-team/cdk8s-cli#1525]
### Description of the bug:
importing a helm chart in OCI image format rather than traditional helm repository does not work as expected. I was not able to find a non-OCI format for this particular chart, and I think more charts are moving this way over time. cdk8s should support this format for the import command.

### Reproduction Steps:
Does not work via cdk8s:
```
> cdk8s import helm:oci://quay.io/strimzi-helm/strimzi-kafka-operator@0.37.0
Error: Error: looks like "oci://quay.io/strimzi-helm" is not a valid chart repository or cannot be reached: object required

    at pullHelmRepo (/usr/local/Cellar/cdk8s/2.134.0/libexec/lib/node_modules/cdk8s-cli/lib/import/helm.js:137:15)
    at new ImportHelm (/usr/local/Cellar/cdk8s/2.134.0/libexec/lib/node_modules/cdk8s-cli/lib/import/helm.js:51:24)
    at ImportHelm.fromSpec (/usr/local/Cellar/cdk8s/2.134.0/libexec/lib/node_modules/cdk8s-cli/lib/import/helm.js:42:16)
    at matchImporter (/usr/local/Cellar/cdk8s/2.134.0/libexec/lib/node_modules/cdk8s-cli/lib/import/dispatch.js:37:34)
    at async importDispatch (/usr/local/Cellar/cdk8s/2.134.0/libexec/lib/node_modules/cdk8s-cli/lib/import/dispatch.js:13:26)
    at async Object.handler (/usr/local/Cellar/cdk8s/2.134.0/libexec/lib/node_modules/cdk8s-cli/lib/cli/cmds/import.js:34:9)
> 
```

Does work via helm:
```
> helm pull oci://quay.io/strimzi-helm/strimzi-kafka-operator
Pulled: quay.io/strimzi-helm/strimzi-kafka-operator:0.37.0
Digest: sha256:55c24e808d5dd1bb406ab63a7c2f33259869ad2a1a01d846a834810a9f5b4d59
```

### Error Log:
Error: Error: looks like "oci://quay.io/strimzi-helm" is not a valid chart repository or cannot be reached: object required

### Environment:

  - **Framework Version**: 2.134.0
  - **OS**: Mac Ventura 13.4.1

### Other:
```
> which cdk8s
/usr/local/bin/cdk8s
> brew info cdk8s
==> cdk8s: stable 2.134.0 (bottled)
Define k8s native apps and abstractions using object-oriented programming
https://cdk8s.io/
/usr/local/Cellar/cdk8s/2.134.0 (10,750 files, 143.6MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-10-11 at 14:44:50
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/c/cdk8s.rb
License: Apache-2.0
==> Dependencies
Required: node ✔
==> Analytics
install: 1,659 (30 days), 4,689 (90 days), 9,738 (365 days)
install-on-request: 1,623 (30 days), 4,596 (90 days), 9,547 (365 days)
build-error: 1 (30 days)
> helm version
version.BuildInfo{Version:"v3.12.1", GitCommit:"f32a527a060157990e2aa86bf45010dfb3cc8b8d", GitTreeState:"clean", GoVersion:"go1.20.4"}
```

---

This is :bug: Bug Report

**Comment by vinayak-kukreja** [comment]
Hey, thank you for reporting this. Taking a look.

**Comment by vinayak-kukreja** [comment]
This is a coverage gap for the feature. Taking a look into implementation.
