### ISSUE TITLE
Support `http_proxy` and `https_proxy` environment variables

### ISSUE THREAD

**Issue by jizusun** [cdk8s-team/cdk8s-cli#246]
In our company, every single HTTP request must be made through our corporate proxy.
We have `http_proxy` and `https_proxy` configured, but the cli doesn't use them.

Shall we support it?

```sh
➜  cdk8s -h
/home/debian/.config/yarn/global/node_modules/cdk8s/lib/_loadurl.js:39
    throw new Error(`http error: ${err.message}`);
    ^

Error: http error: connect ETIMEDOUT 104.16.20.35:80
    at RedirectableRequest.<anonymous> (/home/debian/.config/yarn/global/node_modules/cdk8s/lib/_loadurl.js:39:11)
    at Object.onceWrapper (node:events:646:26)
    at RedirectableRequest.emit (node:events:526:28)
    at ClientRequest.eventHandlers.<computed> (/home/debian/.config/yarn/global/node_modules/cdk8s/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:526:28)
    at Socket.socketErrorListener (node:_http_client:442:9)
    at Socket.emit (node:events:526:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
------------------------------------------------------------------------------------------------
A new version undefined of cdk8s-cli is available (current 1.0.139).
Run "npm install -g cdk8s-cli" to install the latest version on your system.
For additional installation methods, see https://cdk8s.io/docs/latest/getting-started
------------------------------------------------------------------------------------------------
cdk8s [command]

(omitted here ...)
```

But 
```sh
➜  cdk8s -h --check-upgrade false
cdk8s [command]

Commands:
  cdk8s import [SPEC]  Imports API objects to your app by generating constructs.               [aliases: gen, import, generate]
  cdk8s init TYPE      Create a new cdk8s project from a template.
  cdk8s synth          Synthesizes Kubernetes manifests for all charts in your app.                       [aliases: synthesize]

Options:
  --version        Show version number                                                                                [boolean]
  --check-upgrade  Check for cdk8s-cli upgrade                                                        [boolean] [default: true]
  --help           Show help                                                                                          [boolean]

Options can be specified via environment variables with the "CDK8S_" prefix (e.g. "CDK8S_OUTPUT")
```

**Comment by jevyzhu** [comment]
Hi it seems your company is also my company. @jizusun  😺 😄 

I guess  the cli is not using "request"  otherwise your http_proxy should work.

I have a workaround installation script. You can use it to do a "hack" install for cdk8s-cli:

https://gist.github.com/jevyzhu/6efac922e2eb53de1ebfc48a0a835029

**Comment by dvgitit** [comment]
> Hi it seems your company is also my company. @jizusun 😺 😄
> 
> I guess the cli is not using "request" otherwise your http_proxy should work.
> 
> I have a workaround installation script. You can use it to do a "hack" install for cdk8s-cli:
> 
> https://gist.github.com/jevyzhu/6efac922e2eb53de1ebfc48a0a835029

This is a good workaround. Just it seems to produce the same error when cdk8s internally runs `npm import k8s`:

```
Importing k8s v1.25.0...
Importing resources, this may take a few moments...
k8s
Could not find a schema for k8s version 1.25.0. The current list of available schemas is at https://github.com/cdk8s-team/cdk8s/tree/master/kubernetes-schemas.
Error: connect ETIMEDOUT 11.22.33.44:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '11.22.33.44',
  port: 443
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cdk8s-local@1.0.0 import: `cdk8s import`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cdk8s-local@1.0.0 import script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /some/path/.npm/_logs/2022-11-15T14_53_09_888Z-debug.log
Error: error during project initialization: Error: Command failed: npm run import
    at checkExecSyncError (child_process.js:760:11)
    at execSync (child_process.js:833:15)
    at Object.exports.post (/some/path/cdk8s/node_modules/cdk8s-cli/templates/typescript-app/.hooks.sscaff.js:35:3)
    at executePostHook (/some/path/cdk8s/node_modules/sscaff/lib/sscaff.js:81:37)
    at sscaff (/some/path/cdk8s/node_modules/sscaff/lib/sscaff.js:48:15)
    at async Object.handler (/some/path/cdk8s/node_modules/cdk8s-cli/lib/cli/cmds/init.js:55:13)
```

A workaround might be to run `npm import k8s` manually, but that does not seem to be a final solution.

**Comment by jizusun** [comment]
Just found a detailed tutorial to run `nodejs` application with corporate network, hope it can helps.


Running the backend behind a Corporate Proxy: https://github.com/backstage/backstage/blob/master/contrib/docs/tutorials/help-im-behind-a-corporate-proxy.md

**Comment by disaster37** [comment]
Hi,

same matter here.
We need to use it throughtout coorporate proxy.
