### ISSUE TITLE
Import fails with multiline strings

### ISSUE THREAD

**Issue by jpmartin2** [cdk8s-team/cdk8s-cli#264]
I was trying to import the crds from traefik (https://github.com/traefik/traefik-helm-chart/tree/v10.19.4/traefik/crds), but they all fail because they have multi-line strings that cdk8s seems to parse incorrectly. When I try to import them I get errors like this:

```
Error: Key 'of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info' contains non standard characters (Must match regex '/^(\w|\.|\/|-|#|,)*$/')
    at SafeReviver._sanitizeObj (/home/joseph/kubernetes/cdk8s/node_modules/cdk8s-cli/lib/reviver.js:40:23)
    at SafeReviver._sanitizeObj (/home/joseph/kubernetes/cdk8s/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/home/joseph/kubernetes/cdk8s/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/home/joseph/kubernetes/cdk8s/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/home/joseph/kubernetes/cdk8s/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/home/joseph/kubernetes/cdk8s/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/home/joseph/kubernetes/cdk8s/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver._sanitizeObj (/home/joseph/kubernetes/cdk8s/node_modules/cdk8s-cli/lib/reviver.js:47:22)
    at SafeReviver.sanitize (/home/joseph/kubernetes/cdk8s/node_modules/cdk8s-cli/lib/reviver.js:31:14)
    at safeParseYaml (/home/joseph/kubernetes/cdk8s/node_modules/cdk8s-cli/lib/util.js:105:17)
```

Which seems to indicate that cdk8s is trying to parse the continuation line as a new, independent line and not a continuation of the quoted line before.

**Comment by fernandonogueira** [comment]
It's happening here too.
Did you manage to fix it, @jpmartin2 ?
