### ISSUE TITLE
cdk8s v2 incompatible with cdk8s-cli `v1.x`

### ISSUE THREAD

**Issue by Hunter-Thompson** [cdk8s-team/cdk8s-cli#277]
Using the latest version of cdk8s, and cdk8s-cli, the synth process fails.

```
👾 build » default | node .projenrc.js
👾 build » compile | tsc --build
👾 build » post-compile » synth | cdk8s synth
/home/hunter/hunter-os/cdk8s-cli-bug/node_modules/cdk8s/lib/app.js:166
    for (const child of app.node.findAll()) {
                                 ^

TypeError: Cannot read properties of undefined (reading 'findAll')
    at validate (/home/hunter/hunter-os/cdk8s-cli-bug/node_modules/cdk8s/lib/app.js:166:34)
    at App.synth (/home/hunter/hunter-os/cdk8s-cli-bug/node_modules/cdk8s/lib/app.js:89:9)
    at Object.<anonymous> (/home/hunter/hunter-os/cdk8s-cli-bug/lib/main.js:35:5)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47

Node.js v17.7.2
Error: command "node lib/main.js " at /home/hunter/hunter-os/cdk8s-cli-bug returned a non-zero exit code 1
    at ChildProcess.<anonymous> (/home/hunter/hunter-os/cdk8s-cli-bug/node_modules/cdk8s-cli/lib/util.js:50:27)
    at Object.onceWrapper (node:events:642:26)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
👾 Task "build » post-compile » synth" failed when executing "cdk8s synth" (cwd: /home/hunter/hunter-os/cdk8s-cli-bug)
error Command failed with exit code 1.
```

Here is the repository replicated: https://github.com/Hunter-Thompson/cdk8s-bug
Here is the failed action: https://github.com/Hunter-Thompson/cdk8s-bug/runs/6306998493?check_suite_focus=true

related to #237

**Comment by iliapolo** [comment]
@Hunter-Thompson is this still an issue? You should use `2.x` of the cli as well.

**Comment by vinayak-kukreja** [comment]
Hey, looks like we have not heard from you in a while. If this is still an issue, please feel free to open a new issue with us. We do not track comments on a closed issue.
