### ISSUE TITLE
Error while installing CDK8s-CLI

### ISSUE THREAD

**Issue by RafaelMoreira1180778** [cdk8s-team/cdk8s-cli#74]
Node version: v10.19.0

```bash
npm i -g cdk8s-cli                                                 
npm ERR! Unexpected end of JSON input while parsing near '...ff":"^1.2.0","yaml":"'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rafael/.npm/_logs/2021-09-27T12_16_52_583Z-debug.log
```

```bash
tail -50 /home/rafael/.npm/_logs/2021-09-27T12_16_52_583Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', '-g', 'cdk8s-cli' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose npm-session 252abe8b5806e984
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/cdk8s-cli 11ms (from cache)
8 silly fetchPackageMetaData error for cdk8s-cli@latest Unexpected end of JSON input while parsing near '...ff":"^1.2.0","yaml":"'
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 24ms
11 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...ff":"^1.2.0","yaml":"'
11 verbose stack     at JSON.parse (<anonymous>)
11 verbose stack     at parseJson (/usr/lib/nodejs/json-parse-better-errors/index.js:7:17)
11 verbose stack     at consumeBody.call.then.buffer (/usr/share/npm/node_modules/node-fetch-npm/src/body.js:96:50)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
12 verbose cwd /home/rafael
13 verbose Linux 5.13.0-7614-generic
14 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "-g" "cdk8s-cli"
15 verbose node v10.19.0
16 verbose npm  v6.14.4
17 error Unexpected end of JSON input while parsing near '...ff":"^1.2.0","yaml":"'
18 verbose exit [ 1, true ]
```

Got this error today, cannot install the cdk8s-cli. Fresh NPM install.

**Comment by Chriscbr** [comment]
I don't seem to be able to reproduce the exact error, but cdk8s no longer supports Node v10 since it has been deprecated and is no longer receiving security updates. Can you try installing with Node v12.13.0 or above?
