### ISSUE TITLE
Unable to resolve dependency tree

### ISSUE THREAD

**Issue by Almenon** [cdk8s-team/cdk8s-cli#827]
### Description of the bug:

When following https://cdk8s.io/docs/latest/getting-started there is a error when running `cdk8s init typescript-app`

### Reproduction Steps:

```
C:\dev\misc\cdk_test>npm -g list
C:\Users\almenon\AppData\Roaming\npm
`-- npm@9.5.0


C:\dev\misc\cdk_test>node --version
v16.14.2

C:\dev\misc\cdk_test>npm install -g cdk8s-cli

added 154 packages in 6s

15 packages are looking for funding
  run `npm fund` for details

C:\dev\misc\cdk_test>ls -la
total 8
drw-rw-rw-   2 almenon 0 4096 2023-02-21 21:50 .
drw-rw-rw-  10 almenon 0 4096 2023-02-21 21:41 ..

C:\dev\misc\cdk_test>cdk8s init typescript-app
```

### Error Log:

```
Initializing a project from the typescript-app template
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: cdk_test@1.0.0
npm ERR! Found: constructs@10.1.256
npm ERR! node_modules/constructs
npm ERR!   constructs@"10.1.256" from the root project
npm ERR!   peer constructs@"^10" from cdk8s@2.7.8
npm ERR!   node_modules/cdk8s
npm ERR!     cdk8s@"2.7.8" from the root project
npm ERR!     peer cdk8s@"^2.7.8" from cdk8s-plus-25@2.4.32
npm ERR!     node_modules/cdk8s-plus-25
npm ERR!       cdk8s-plus-25@"2.4.32" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer constructs@"^10.1.257" from cdk8s-plus-25@2.4.32
npm ERR! node_modules/cdk8s-plus-25
npm ERR!   cdk8s-plus-25@"2.4.32" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\almenon\AppData\Local\npm-cache\_logs\2023-02-22T05_50_33_070Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\almenon\AppData\Local\npm-cache\_logs\2023-02-22T05_50_33_070Z-debug-0.log
Error: error during project initialization: Error: Command failed: npm install  cdk8s@^2.7.8 cdk8s-plus-25@^2.4.32 constructs@^10.1.256
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:902:15)
    at installDeps (C:\Users\almenon\AppData\Roaming\npm\node_modules\cdk8s-cli\templates\typescript-app\.hooks.sscaff.js:44:3)
    at Object.exports.post (C:\Users\almenon\AppData\Roaming\npm\node_modules\cdk8s-cli\templates\typescript-app\.hooks.sscaff.js:15:3)
    at executePostHook (C:\Users\almenon\AppData\Roaming\npm\node_modules\cdk8s-cli\node_modules\sscaff\lib\sscaff.js:81:37)
    at sscaff (C:\Users\almenon\AppData\Roaming\npm\node_modules\cdk8s-cli\node_modules\sscaff\lib\sscaff.js:48:15)
    at async Object.handler (C:\Users\almenon\AppData\Roaming\npm\node_modules\cdk8s-cli\lib\cli\cmds\init.js:55:13)
STDOUT:
undefined
STDERR:
undefined
    at Object.handler (C:\Users\almenon\AppData\Roaming\npm\node_modules\cdk8s-cli\lib\cli\cmds\init.js:59:19)
```

### Environment:

  - **Framework Version**: latest
  - **OS**: Windows (and yes, I have `ls` on Windows cmd, it's via https://github.com/bmatzelle/gow)

### Other:

---

This is :bug: Bug Report

**Comment by Almenon** [comment]
It looks like as a result of this the package.json is generated without any packages installed. No node_modules directory is present.

```json
{
  "name": "cdk_test",
  "version": "1.0.0",
  "main": "main.js",
  "types": "main.ts",
  "license": "Apache-2.0",
  "private": true,
  "scripts": {
    "import": "cdk8s import",
    "synth": "cdk8s synth",
    "compile": "tsc --build",
    "watch": "tsc --build -w",
    "test": "jest",
    "build": "npm run compile && npm run test && npm run synth",
    "upgrade": "npm i cdk8s@latest cdk8s-cli@latest",
    "upgrade:next": "npm i cdk8s@next cdk8s-cli@next"
  }
}
```

Running `npm i cdk8s@latest --save` works without issue.

**Comment by eno-conan** [comment]
@sumupitchayan 
when will I run command? : `npm i cdk8s@latest --save`

```
npm install -g cdk8s-cli
// <- here?
mkdir hello
cd hello
cdk8s init typescript-app
// <- here?
```

I refer to the article below
https://cdk8s.io/docs/latest/getting-started/#prerequisites

**Comment by sumupitchayan** [comment]
@eno-conan Can you try doing it before initializing the cdk8s app? 

```
npm install -g cdk8s-cli

npm i cdk8s@latest --save

mkdir hello
cd hello
cdk8s init typescript-app
```

**Comment by eno-conan** [comment]
@sumupitchayan

tried doing
```
npm install -g cdk8s-cli

npm i cdk8s@latest --save

mkdir hello
cd hello
cdk8s init typescript-app
```

but the same result 

```
$ cdk8s init typescript-app
Initializing a project from the typescript-app template
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: hello@1.0.0
npm ERR! Found: constructs@10.2.0
npm ERR! node_modules/constructs
npm ERR!   constructs@"10.2.0" from the root project
npm ERR!   peer constructs@"^10" from cdk8s@2.7.56
npm ERR!   node_modules/cdk8s
npm ERR!     cdk8s@"2.7.56" from the root project
npm ERR!     peer cdk8s@"^2.7.56" from cdk8s-plus-25@2.7.3
npm ERR!     node_modules/cdk8s-plus-25
npm ERR!       cdk8s-plus-25@"2.7.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer constructs@"^10.2.1" from cdk8s-plus-25@2.7.3
npm ERR! node_modules/cdk8s-plus-25
npm ERR!   cdk8s-plus-25@"2.7.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
    at sscaff (C:\Users\eno-conan\AppData\Roaming\npm\node_modules\cdk8s-cli\node_modules\sscaff\lib\sscaff.js:48:15)
    at async Object.handler (C:\Users\eno-conan\AppData\Roaming\npm\node_modules\cdk8s-cli\lib\cli\cmds\init.js:55:13)
STDOUT:
undefined
STDERR:
undefined
    at Object.handler (C:\Users\eno-conan\AppData\Roaming\npm\node_modules\cdk8s-cli\lib\cli\cmds\init.js:59:19)
```

**Comment by iliapolo** [comment]
Highly bizarre..what happens here is that npm thinks it needs to install two different versions of the `constructs` library:

- 10.2.0 (Pinned direct)
- ^10.2.1 (Caret transitive)

These two cannot co-exist. Fro posterity, we can reproduce this by running:

```console
npm install "cdk8s@^2.7.56" "cdk8s-plus-25@^2.7.3" "constructs@10.2.0"
```

The weird thing is though that the init template always [uses carets](https://github.com/cdk8s-team/cdk8s-cli/blob/2.x/templates/typescript-app/.hooks.sscaff.js#L15), so the command should always be:

```console
npm install "cdk8s@^2.7.56" "cdk8s-plus-25@^2.7.3" "constructs@^10.2.0"
```

Which does succeed. The fact both this issue as well as its [duplicate](https://github.com/cdk8s-team/cdk8s-cli/issues/900) use windows, makes me think the problem here is with some shell escaping when we run the [command](https://github.com/cdk8s-team/cdk8s-cli/blob/2.x/templates/typescript-app/.hooks.sscaff.js#L45)

> Also see https://github.com/pnpm/pnpm/issues/4940


@sumupitchayan We can fix this by removing the need to run `npm install <library>`, and instead just write the correct versions in the `package.json` file, and run `npm install`.

**Comment by Almenon** [comment]
Thanks!
