### ISSUE TITLE
Import CRD fails with "Error: unsupported array type undefined"

### ISSUE THREAD

**Issue by JFReuter-Fin** [cdk8s-team/cdk8s-cli#93]
### Description of the bug:

When importing the CRDs from the argo-workflows project, cdk8s import errors out.

### Reproduction Steps:

1. Run the following command: `cdk8s import https://raw.githubusercontent.com/argoproj/argo-workflows/v2.12.9/manifests/base/crds/full/argoproj.io_clusterworkflowtemplates.yaml`

### Error Log:
```
Importing resources, this may take a few moments...
argoproj.io
  argoproj.io/clusterworkflowtemplate
Error: unsupported array type undefined
    at TypeGenerator.typeForArray (/usr/local/lib/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:397:19)
    at TypeGenerator.emitArray (/usr/local/lib/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:257:25)
    at TypeGenerator.emitTypeInternal (/usr/local/lib/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:183:29)
    at TypeGenerator.typeForProperty (/usr/local/lib/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:376:21)
    at TypeGenerator.typeForArray (/usr/local/lib/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:399:21)
    at TypeGenerator.emitArray (/usr/local/lib/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:257:25)
    at TypeGenerator.emitTypeInternal (/usr/local/lib/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:183:29)
    at TypeGenerator.typeForProperty (/usr/local/lib/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:376:21)
    at TypeGenerator.emitProperty (/usr/local/lib/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:319:35)
    at /usr/local/lib/node_modules/cdk8s-cli/node_modules/json2jsii/lib/type-generator.js:299:22
```

### Environment:

  - cdk8s: 1.0.0-beta.67:
  - wsl/ubuntu:

---

This is :bug: Bug Report

**Comment by iliapolo** [comment]
@ajkaanbal Thanks, we will take a look 👍

**Comment by iliapolo** [comment]
Keep

**Comment by adrianord** [comment]
I ran into this problem today using `node v16.14.1` and `cdk8s-cli 1.0.161` with the argo workflows CRDs

https://raw.githubusercontent.com/argoproj/argo-workflows/master/manifests/base/crds/full/argoproj.io_workflows.yaml

**Comment by iliapolo** [comment]
We should probably fallback to `any` in `json2jsii` for scenarios like these.

**Comment by darklore** [comment]
Same error using `node v18.10.0` and `cdk8s-cli 2.1.4`.

cdk8s.yaml
```
language: go
app: go run .
imports:
  - https://raw.githubusercontent.com/argoproj/argo-workflows/v3.4.1/manifests/base/crds/full/argoproj.io_clusterworkflowtemplates.yaml
```

**Comment by vinayak-kukreja** [comment]
Keep open.
